title: ProdIsMyDev
email: chris@casualcompany.de
description: >-
  A curated list of hurdles I overcame in my daily life as a Developer.
baseurl: ""
url: "https://blog.prodismy.dev"
twitter_username: ProdIsMyDev
github_username:  ProdIsMyDev

theme: minima
plugins:
  - jekyll-feed